### ISSUE TITLE
Seq did not match templates

### ISSUE THREAD

**Issue by jaarribere** [RNAcentral/r2dt-web#10]
Hello--I have an rRNA sequence that didn't match any of the templates. I suspect it *could* work, but there's too high a mutation rate and it's throwing the program for a loop. Any hope?

**Comment by AntonPetrov** [comment]
👋 Hi @jaarribere! Thank you for your question!

The mutation rate is usually not a problem for R2DT, so it's hard to know without seeing the sequence what could be the issue. It could be that the sequence is too short if it's a partial rRNA, or it could be too long if it has one or more introns. Or maybe it has too many Ns or other ambiguous nucleotides?

I am happy to investigate more if you are okay with sharing the sequence - here on GitHub or by email `contact @ antonpetrov.com`. Thanks for using R2DT!

**Comment by AntonPetrov** [comment]
The issue was resolved over email. A permanent fix will be implemented in https://github.com/RNAcentral/R2DT/issues/75
