### ISSUE TITLE
Add link to editor for R2DT results

### ISSUE THREAD

**Issue by blakesweeney** [RNAcentral/r2dt-web#12]
Caeden has recently developed an editor for the diagrams R2DT produces. We should add a button on the r2dt results pages that opens up the editor. It is at: <https://ldwlab.github.io/XRNA-TypeScript/> and can be opened with an r2dt result using the following url: <https://ldwlab.github.io/XRNA-TypeScript/?r2dt_job_id=r2dt-R20230111-203900-0332-91533423-p1m>. Basically just set the `r2dt_job_id` param to the job id in question.

**Comment by AntonPetrov** [comment]
This is done now
