### ISSUE TITLE
Support template-free mode

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/r2dt-web#14]
@blakesweeney As discussed, here is a short description of the requirements for the `r2dt-web` widget for the new R2DT.

Starting with the next version 1.4, R2DT will have a [new template-free mode](https://docs.r2dt.bio/en/latest/usage.html#template-free-visualisation). Instead of selecting a template and predicting the secondary structure, R2DT will accept a user-provided structure and use it to generate the usual output.

In order to support this, the following changes in the web app are needed:

1) Validate secondary structure in dot-bracket format (including pseudoknots), if provided. Example format:

```
>3SKZ_B
GGCCUUAUACAGGGUAGCAUAAUGGGCUACUGACCCCGCCUUCAAACCUAUUUGGAGACUAUAAGGUC
.((((((((A..((((((.....BB))))))(.....a)(((((((bb..)))))))..)))))))).
```

Validation checks:
- the structure must have the same length as the sequence
- the number of open and closing parentheses must be the same 

In theory, more advanced pseudoknot parsing (accepting the `AABBaabb` notation as well as `[]` ) should be done but it's not a priority.

2) Submit to a new template-free API endpoint or use a new parameter to run R2DT in template-free mode. I will post further details about this once the new API is available.

3) If a dot-bracket structure is provided, the Advanced options, such as _Selecting a template_ or _Constrained folding_ should not be editable by the user.

4) Provide a new example (possibly the one provided above).

The new R2DT version will go live in the next couple of weeks and can be deployed on the RNAcentral website whenever the new widget is ready.

**Comment by carlosribas** [comment]
This has already been done
