### ISSUE TITLE
Add an option to hide title

### ISSUE THREAD

**Issue by AntonPetrov** [RNAcentral/r2dt-web#17]
Based on [feedback from PomBase](https://github.com/RNAcentral/R2DT/issues/137) from @valwood and @kimrutherford, it would be useful to add an option for hiding the `Secondary structure` heading. Currently this can be accomplished by setting the `titleSize` to 0px but there should be a more official way of accomplishing this.

**Comment by carlosribas** [comment]
I'll think of an alternative, but it will most likely work the same way, for example `"hideTitle": "true"`. I'll be in touch as soon as it's finished

**Comment by carlosribas** [comment]
Ok, this can be done using the following parameter:

```
customStyle='{
    "hideTitle": "true"
}'
```

**Comment by kimrutherford** [comment]
Thanks!  I've just tested that option and it works for us.

@ValWood The change will be on pombase.org in the morning.
