### ISSUE TITLE
2D structures not showing

### ISSUE THREAD

**Issue by VMJarocki** [RNAcentral/r2dt-web#4]
When I have tried viewing the 23S and 16S Mycoplasma bovis 2D structures I receive the following error message:
"There was an error. Let us know if the problem persists by raising an issue on GitHub."

**Comment by blakesweeney** [comment]
Thank you for reaching out to us. I just took a quick look and found this sequence: https://rnacentral.org/rna/URS00022109E4/28903 is showing the problem you mention. Is this the sequence you were looking at? We will look into the issue and try to resolve it for you. Thanks!

**Comment by AntonPetrov** [comment]
In the meantime, please feel free to use the [R2DT web application](https://rnacentral.org/r2dt) to analyse the sequences you are interested in. For example, for [URS00022109E4_28903](https://rnacentral.org/rna/URS00022109E4/28903) the sequence page shows an error, but the web application shows a secondary structure as expected:
https://rnacentral.org/r2dt?jobid=r2dt-R20220119-102425-0097-95300304-p2m

**Comment by carlosribas** [comment]
Hi @VMJarocki, you should be able to see the 2D structures now, please clear your cache and try again. In case you still get an error message, send me the URL so I can debug

**Comment by VMJarocki** [comment]
All good now 😊
Cheers!

[photo]
Veronica Jarocki PhD
Research Associate, ithree institute, UTS
+61 411888474<tel:+61%20411888474> | ***@***.******@***.***>

***@***.***<http://www.linkedin.com/in/veronica-jarocki-a13863160>
***@***.***<http://twitter.com/VMJarocki>

**Comment by AntonPetrov** [comment]
Perfect, thanks @VMJarocki. Feel free to reach out if you run into any problems in the future.
