### ISSUE TITLE
my seq did not match selected template

### ISSUE THREAD

**Issue by FCo2GNT** [RNAcentral/r2dt-web#6]
Hi,
I would like to visualize the 2ndary structure of a RNA sequence , based on a U7snRNA template (mus musculus). But this is not working with the current setup of the tool.
do you have any advice?

**Comment by AntonPetrov** [comment]
Hi @FCo2GNT! 

Thank you for reaching out! If you are okay with sharing the sequence that did not work here or by [email](https://www.ebi.ac.uk/about/people/anton-petrov), I can debug this and try to generate a diagram. If the sequence is private, my guess would be that it could contain large insertions that confuse R2DT, but without looking at a specific case, it's hard to tell.

**Comment by FCo2GNT** [comment]
Thank you very much for your answer, unfortunately I cannot share with you this sequence.
My seq is 443bp , so there are no large insertions compared to the original U7 snRNA structure, but probably the modifications that we made are enough to confuse the tool…
I will try to see if I can overcome this,
Again, thank you

**Comment by AntonPetrov** [comment]
Of course, I understand. 

For U7 snRNA, R2DT uses the [RF00066 Rfam family](https://rfam.xfam.org/family/RF00066#tabview=tab3) as a template, which is much smaller than 443 bps (in human, U7 is only 63 nucleotides, for example). This is the most likely explanation for the problem.
